# Generated by Django 5.1.6 on 2026-02-20 08:58

from django.db import migrations


def seed(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Post = apps.get_model("comments", "Post")
    Comment = apps.get_model("comments", "Comment")
    Like = apps.get_model("comments", "Like")

    u1, _ = User.objects.get_or_create(username="demo1", defaults={"email": "demo1@example.com"})
    u2, _ = User.objects.get_or_create(username="demo2", defaults={"email": "demo2@example.com"})

    p1, _ = Post.objects.get_or_create(author=u1, title="First post", defaults={"content": "Hello!"})
    p2, _ = Post.objects.get_or_create(author=u2, title="Second post", defaults={"content": "Hi there!"})

    c1, _ = Comment.objects.get_or_create(post=p1, author=u2, defaults={"content": "Nice post!"})
    c2, _ = Comment.objects.get_or_create(post=p2, author=u1, defaults={"content": "Thanks!"})

    Like.objects.get_or_create(user=u1, post=p2)
    Like.objects.get_or_create(user=u2, post=p1)
    Like.objects.get_or_create(user=u1, comment=c1)


def unseed(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=["demo1", "demo2"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_likes_like_like_exactly_one_target_and_more"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]